#!/usr/bin/env ansible-playbook
---
- name: Install k3s in lxc/lxd
  hosts: all
  become: yes

  # pre_tasks:
  #   - name: Resolve Ansible dependencies
  #     command: ansible-galaxy install -r requirements.yml
  #     environment:
  #       ANSIBLE_CONFIG: "{{ playbook_dir }}/ansible.cfg"
  #     register: _result
  #     changed_when: ("was installed successfully" in _result.stdout)

  roles:
    - install_lxd
    - create_lxc_environment
    - create_k3s_cluster
